%YAML:1.0

# enum camera_type
# {
#     MONOCULAR,
#     STEREO,
#     RGBD,
#     THERMAL,
#     LIDAR,
#     UNKNOWN
# };
imu_topic: "/imu_data_raw"

sensor_list: ['cam0','cam1']

cam_0:
  sensor_type: 0
  left_image_topic: "/fisheye/left/image_raw"
  frame_id: "cam0"
  camera_config_file: "/home/yy/mono_ws/src/MCVIO_CPU_only/MCVIO/config/MCVIO/cam360/cam_0.yaml"
  extrinsicRotation_imu_camera: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [-2.8833749665917896e-02, -0.014116195676831, -0.99948454110097,
            -0.999573886335575, 0.004954022403771, 0.028766359137359,
            0.00454537366421, 0.999888091038267,  -1.4252893674741474e-02]
  #Translation from camera frame to imu frame, imu^T_cam
  extrinsicTranslation_imu_camera: !!opencv-matrix
    rows: 3
    cols: 1
    dt: d
    data: [-2.9964041980699994e-02, 0.0163323829651326, -4.2422324053882229e-02] 
  #feature traker paprameters
  max_cnt: 200          # max feature number in feature tracking
  min_dist: 20            # min distance between two features
  freq: 13                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
  F_threshold: 1.0        # ransac threshold (pixel)
  show_track: 1           # publish tracking image as topic
  equalize: 1             # if image is too dark or light, trun on equalize to find enough features
  fisheye: 1             # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points
  fisheye_path: "/home/yy/mono_ws/src/MCVIO_CPU_only/MCVIO/config/MCVIO/fisheye_mask.jpg"
  image_width: 1088
  image_height: 1280
  mirror_parameters:
    xi: 1.9370645285718184
  distortion_parameters:
    k1: -0.030101416027143404
    k2: 0.2030609832189508
    p1: -0.00017036850596376823
    p2: -0.0009683462814614623
  projection_parameters:
    fx: 571.1375267362884
    fy: 573.7579044576655
    cx: 417.4754436701555
    cy: 344.6485017643427

cam_1:
  sensor_type: 0
  left_image_topic: "/fisheye/right/image_raw"
  frame_id: "cam1"
  camera_config_file: "/home/yy/mono_ws/src/MCVIO_CPU_only/MCVIO/config/MCVIO/cam360/cam_1.yaml"
  extrinsicRotation_imu_camera: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [0.00737952285903512, 0.008165246582117036, -0.9999394338611853,
            -0.9999715030270758, 0.0016526595125707089, -0.00736626433872406,
            0.001592412052650538, 0.9999652981302853, 0.008177209735957536]
  #Translation from camera frame to imu frame, imu^T_cam
  extrinsicTranslation_imu_camera: !!opencv-matrix
    rows: 3
    cols: 1
    dt: d
    data: [-3.4347897673480746e-02, 0.00916004706814275, -4.7328617761588788e-02]
  #feature traker paprameters
  max_cnt: 200          # max feature number in feature tracking
  min_dist: 20            # min distance between two features
  freq: 13                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
  F_threshold: 1.0        # ransac threshold (pixel)
  show_track: 1           # publish tracking image as topic
  equalize: 1             # if image is too dark or light, trun on equalize to find enough features
  fisheye: 1             # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points
  fisheye_path: "/home/yy/mono_ws/src/MCVIO_CPU_only/MCVIO/config/MCVIO/fisheye_mask.jpg"
  image_width: 1088
  image_height: 1280
  mirror_parameters:
    xi: 1.8075725317445792
  distortion_parameters:
    k1: -0.10312403240397729
    k2: 0.1922063596449809
    p1: 0.0003807523836658894
    p2: -0.0005500919525955383
  projection_parameters:
    fx: 547.8836937046682
    fy: 549.2551986948349
    cx: 413.04391004954954
    cy: 347.83565317286997